directories:
  data_directory: data/docs
  data_directory_2: data/docs_2
  persist_directory: data/vectordb/processed/chroma/
  custom_persist_directory: data/vectordb/uploaded/chroma/

embedding_model_config:
  engine: "sentence-transformers/all-MiniLM-L6-v2"  

llm_config:
  engine: "llama3-8b-8192" 
  temperature: 0.0
  max_token: 4096
  llm_system_role: >
    You are a chatbot. You'll receive a prompt that includes a chat history, retrieved content from the vectorDB based on the user's question, and the source.
    Your task is to respond to the user's new question using the information from the vectorDB without relying on your own knowledge.

    # Chat history:
    [user query, response]

    # Retrieved content number:
    Content

    Source

    # User question:
    New question

summarizer_config:
  max_final_token: 3000
  character_overlap: 100
  token_threshold: 0
  summarizer_llm_system_role: >
    You are an expert text summarizer. You will receive a text and your task is to summarize and keep all the key information.
    Keep the maximum length of summary within {} number of tokens.
  final_summarizer_llm_system_role: >
    You are an expert text summarizer. You will receive a text and your task is to give a comprehensive summary and keep all the key information.

splitter_config:
  chunk_size: 1500
  chunk_overlap: 500

retrieval_config:
  k: 3

memory:
  number_of_q_a_pairs: 2

serve:
  port: 8000
